dictionary = (
    {  
'input': '''Create a simple web application using python and flask.  The web application should render a single page divided into two vertical halves.  On page load the 
 user should be able to put in a link to a pdf or webpage, click a submit button and have the application convert that pdf or webpage to text and display that pdf or webpage.  on the left side of the screen.  the right side of the screen is reserved for other functionality.
 The page should have a dark theme, with attractive modern styling.''',
'n': 3,
'previous_work': None,

'pass': 'Yes\n', 
'webpage_errors': '', 
'previous_work': None, 
'webpage_code': 'code', 
'code_pass': 'code_pass', 
'code_pass_reason': 'code_pass_reason', 
'task_1': 'I need to create a data layer to store chats. \n\n', 
'task_2': 'I need to create a service layer to call LLM APIs, process results and implement business logic. \n\n', 
'task_3': 'I need to create a client layer with a webpage for user interaction. \n\n', 
'task_4': 'I need to divide the main page into two sections: the left navigation, which will contain a history of previous chats, and the main page, which will be split into two horizontal halves. \n\n', 
'task_5': 'I need to create the top half of the main page to display text from an article that the user will read and scroll through. \n\n', 
'task_6': 'I need to create an interactive menu of options for the user to highlight and right click into the text. \n\n', 
'task_7': 'I need to create the bottom half of the main page to be dynamically generated text based on the actions selected in the top half. \n\n', 
'goal': 'Create a data layer to store chats in a database using a query to a large language model. \n\n', 
'success_criteria_1': 'The data layer should be able to store chats in a database. \n\n', 
'success_criteria_2': 'The data layer should be able to query a large language model. \n\n', 
'success_criteria_3': 'The data layer should be able to store the results of the query in the database. \n\n', 
'success_criteria_4': 'The data layer should be able to retrieve the stored chats from the database. \n\n',
'tasks': ['task_1: I need to create a data layer to store chats. \n\n', 'task_2: I need to create a service layer to call LLM APIs, process results and implement business logic. \n\n', 'task_3: I need to create a client layer with a webpage for user interaction. \n\n', 'task_4: I need to divide the main page into two sections: the left navigation, which will contain a history of previous chats, and the main page, which will be split into two horizontal halves. \n\n', 'task_5: I need to create the top half of the main page to display text from an article that the user will read and scroll through. \n\n', 'task_6: I need to create an interactive menu of options for the user to highlight and right click into the text. \n\n', 'task_7: I need to create the bottom half of the main page to be dynamically generated text based on the actions selected in the top half. \n\n'],
'current_task':'task_1: I need to create a data layer to store chats.',
'criteria': ['success_criteria_1 : The data layer should be able to store chats in a database. \n\n', 'success_criteria_2: The data layer should be able to query a large language model. \n\n', 'success_criteria_3: The data layer should be able to store the results of the query in the database. \n\n', 'success_criteria_4: The data layer should be able to retrieve the stored chats from the database. \n\n'],
  'designs':[],
  'design_output_choice': 'output option 2\n                    ', 
  'reason_for_choice': 'This output option best meets the goals and success criteria of the task. It includes a left navigation menu with a library of chats, a main page with a chat box with a button to send chats and space to see responses along with the chat history with a timestamp, and a button to save the chat, at which point it is added to the list on the left navigation. Additionally, the color scheme is designed to remind the user of a forest on a sunny summer day.', 
  'output': 'Design: The website will have a left navigation menu with a library of chats and a main page with a chat box. The chat box will have a button to send chats and space to see responses along with the chat history with a timestamp. There will also be a button to save the chat, at which point it is added to the list on the left navigation. The color scheme will be generated by the AI using a combination of colors that will remind the user of a beach on a sunny summer day.\n\n', 
  'title': 'Website Design Specification\n\n                    ', 
  'summary': 'This document outlines the design specifications for a website with a left navigation menu, a main page with a chat box, and a color scheme generated by an AI. \n\n                    ', 
  'output_format': 'The website will have a left navigation menu with a library of chats and a main page with a chat box. The chat box will have a button to send chats and space to see responses along with the chat history with a timestamp. There will also be a button to save the chat, at which point it is added to the list on the left navigation. The color scheme will be generated by the AI using a combination of colors that will remind the user of a beach on a sunny summer day.\n\n                    ', 
  'components': '- Left navigation menu\n                    - Main page\n                    - Chat box\n                    - Button to send chats\n                    - Space to see responses\n                    - Chat history with a timestamp\n             - Button to save the chat\n                    - Color scheme generated by AI\n\n                    ', 
  'sequence_of_steps_to_complete_output':       '1. Create left navigation menu with a library of chats.\n                    2. Create main page with a chat box.\n                    3. Add a button to send chats and space to see responses along with the chat history with a timestamp.\n                    4. Add a button to save the chat, at which point it is added to the list on the left navigation.\n                    5. Generate a color scheme using a combination of colors that will remind the user of a beach on a sunny summer day.\n\n                    '
  }
)
